### ISSUE TITLE
Inspector: Make Document Tab changeable

### ISSUE THREAD

**Issue by TheSteveK** [Automattic/isolated-block-editor#114]
It appears that the word "Documented" is hardcoded in the inspector sidebar tabs:

<img width="290" alt="Screen Shot 2022-04-01 at 10 07 43 AM" src="https://user-images.githubusercontent.com/12895386/161280221-1df8725c-4ba8-4458-866a-761f2aa4c1b0.png">

We have a use case to change that for our implementation in Crowdsignal.  In our case we'd like to change it to "Project"  In the WordPress.com Gutenberg implementation it changes to Post or Page depending on what the user is doing.

Is there a way to make this changeable via .iso settings?

**Comment by johngodley** [comment]
It should be possible right now! It was fixed in #111 as part of the `documentInspector` setting.

**Comment by TheSteveK** [comment]
Great I'll check with the team to see if we need to update our packages

**Comment by johngodley** [comment]
I'll close this for now, but please reopen if there's more you need.
