### ISSUE TITLE
Toolbar Options click breaks isolated block editor

### ISSUE THREAD

**Issue by BenniMooris** [Automattic/isolated-block-editor#150]
Whenever i click the dotted options button on the toolbar of a block it results in the error message:

```
TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList
```
I am not sure what to do here. configuration is:

```
wp.attachEditor(textArea, {
      iso: {
        blocks: {
          allowBlocks: [
            'paragraph', 'heading', 'list', 'quote', 'code', 'pullquote', 'table',
            'image', 'gallery', 'audio', 'cover', 'media-text',
            'buttons', 'columns', 'page-break', 'separator', 'spacer',
            'embed/youtube'
          ].map(name => `core/${name}`)
        },
        moreMenu: false
      }
    })
```

**Comment by johngodley** [comment]
How are you loading Gutenberg - separately or bundled together? If separately what version of Gutenberg are you using?

Does the button work in the editor in `yarn storybook`?

**Comment by BenniMooris** [comment]
@johngodley wow thanks for the fast response! i am using the [build-browser](https://github.com/Automattic/isolated-block-editor/blob/trunk/build-browser/isolated-block-editor.js) version of isolated block editor and added react and react-dom in version 17 as it was mentioned here: https://github.com/Automattic/isolated-block-editor#standalone-module

**Comment by BenniMooris** [comment]
just to provide more context maybe this will help:
![image](https://user-images.githubusercontent.com/78963965/170223180-9dbbfc4c-0dc5-41d7-a1f5-0c1c01aeb37a.png)

**Comment by BenniMooris** [comment]
tested the storybook with a downloaded version and it works:
![image](https://user-images.githubusercontent.com/78963965/171158396-08c604d3-3215-4d86-8a62-580d94096db5.png)

**Comment by johngodley** [comment]
The storybook version uses the same single build so it should behave the same. I would start by stripping your `attachEditor` usage back to the most minimal example and see if that changes anything.

If you click the error lines above then it may provide some more information about where the error is occuring.

**Comment by BenniMooris** [comment]
> The storybook version uses the same single build so it should behave the same. I would start by stripping your `attachEditor` usage back to the most minimal example and see if that changes anything.
> 
> If you click the error lines above then it may provide some more information about where the error is occuring.

ok i guess it's because i am rendering the isolated editor within a newly created iframe because when i render it within the current page context it collides with the active styles but it works so i have to figure out why it breaks within an iframe:
![image](https://user-images.githubusercontent.com/78963965/171629078-e48e343b-7bab-458e-aa4b-c72d8dbe55ac.png)

thank you for your time and help!

**Comment by BenniMooris** [comment]
got it to work. had to actually append the script which requires the bundled version to the iframe document. i created the iframe and appended a textarea which then renders the isolated block editor to the textarea from outside the iframe. guess this caused some issues so i changed it to append a script into the iframe document's head and renders the editor to the textarea i created earlier. now everything works. thanks again!
