### ISSUE TITLE
Some error about sidebarIsOpened occurred after upgrading from 2.12.1 to 2.15.0

### ISSUE THREAD

**Issue by alextsoi** [Automattic/isolated-block-editor#163]
I used to use some code below, and the editor can be displayed and used ( I integrated this into a React application )
```
<IsolatedBlockEditor
                            onLoad={(parse) => loadEditorContent(parse)}
                            onSaveContent={(content) => updateBeingEditedContent(content)}
                            settings={{}}
                            onError={() => document.location.reload()}
                        >
                        </IsolatedBlockEditor>
```

However, after upgrading from 2.12.1 to 2.15.0, I got some errors
![Screenshot 2022-06-23 at 2 48 36 PM](https://user-images.githubusercontent.com/16984543/175234695-6558442f-624b-43a6-8538-214c18afc82b.png)

Does anyone has similar issue about this? My react version is 17.0.2

Thank you

**Comment by johngodley** [comment]
Thanks. We've run into this ourselves too, and are looking into it. Stay tuned!

**Comment by johngodley** [comment]
You may have another version of some @wordpress packages in your project, and this could be causing this error.

**Comment by adrianhm13** [comment]
Quite weird, It happened to me too in 2.15.0, then I've jumped in a fresh project directly to 2.16.0, this way it worked fine. 

Now I've tried to implement it directly to my personal project (2.16.0v) to keep developing with the editor but it blowed up with the same error as the picture. I've compared my fresh project package.lock to check the packages from @Wordpress and are the same version. Any insights about this?

EDIT:
In the end it was a different package, I slipped it out. it seems like @wordpress/preferences (2.5.0) it's breaking it. After installing the version 2.4.0 everything works fine again

so @alextsoi you could try to delete the package.lock and node_modules and try again with npm ci to avoid the missmatching versions

thanks for pointing out @johngodley

**Comment by alextsoi** [comment]
@adrianhm13 Thanks!!!, I downgraded to 2.4.0, it works fine. Thank you.

**Comment by timvandesteeg** [comment]
Keep getting the same error as in the screenshot (`Cannot destructure property 'sidebarIsOpened'`), but downgrading @wordpress/preferences 2.4.0 doesn't seem to solve it. 

Can somebody provide a working package.json?

**Comment by alextsoi** [comment]
@timvandesteeg 
This is part of my package.json setting
I included @wordpress packages into my project because I am extending something on the editor.
I guess you use `overrides` to solve your problem.

Thank you.
```
"dependencies": {
    "@automattic/isolated-block-editor": "^2.16.0",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@wordpress/block-editor": "9.4.0",
		"@wordpress/block-library": "7.9.0",
		"@wordpress/blocks": "11.11.0",
		"@wordpress/components": "19.14.0",
		"@wordpress/core-data": "4.10.0",
		"@wordpress/data": "6.12.0",
		"@wordpress/editor": "12.11.0",
		"@wordpress/hooks": "3.12.0",
    "antd": "^4.21.7",
    "axios": "^0.25.0",
    "dot-object": "^2.1.4",
    "moment": "^2.29.1",
    "qs": "^6.10.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "sass": "^1.49.0",
    "underscore": "^1.13.2",
    "web-vitals": "^2.1.4"
  },
  "overrides": {
    "@wordpress/preferences": "2.4.0"
  }
```

**Comment by timvandesteeg** [comment]
Thanks a lot for the reply!
Updating npm and node to the newest version did solve it for me in the end.

**Comment by jonwaldstein** [comment]
I'm getting this error on the latest version `2.23.1`

Below are my deps.  Any ideas?

<img width="487" alt="Screenshot 2023-02-17 at 3 13 31 PM" src="https://user-images.githubusercontent.com/10138447/219784244-8041949b-db6a-48dd-9a90-0b6b64c2682b.png">

**Comment by johngodley** [comment]
The same as the above solutions. There may be a package that you need to upgrade or downgrade.

**Comment by jonwaldstein** [comment]
@johngodley I tried upgrading & downgrading packages - still no luck.  Zooming in on the issue it looks like this line coming from the customized block-editor is undefined.  Do you know where this is being defined upstream? (looks like from the `'isolated/editor'` redux store but i'm not sure if it's defined in another package).  

```
!!select(interfaceStore).getActiveComplementaryArea('isolated/editor')
```

<img width="1089" alt="Screenshot 2023-02-20 at 9 54 33 AM" src="https://user-images.githubusercontent.com/10138447/220150462-ed6cdd7f-3a62-4cab-a784-8b71d6ab71ce.png">

**Comment by johngodley** [comment]
It comes from Gutenberg. You should use the same versions defined in the package.json here as newer versions are untested and it is possible something may have changed.

**Comment by vvvctr** [comment]
Hey @johngodley, I'm a little bit confused about your last comment as I don't have any other packages explicitlly listed in my dependencies. Here is my package.json; it is a new React project generated with CRA:

```json
{
  "name": "cra",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@automattic/isolated-block-editor": "^2.23.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

As you can see my only dependency is `@automattic/isolated-block-editor`, so I don't really know what other package I should try to downgrade/upgrade to make it work.

Thank you for your help!

```bash
❯ node --version
v19.7.0

❯ npm --version                                 
9.5.0
```

**Comment by johngodley** [comment]
@vvvctr the comment likely wasn't aimed at your specific situation, which may be different. What problem are you seeing? How are you loading Gutenberg? It may be worth starting a new issue

**Comment by vvvctr** [comment]
@johngodley I see. The thing is I am getting the same errors reported in this issue. I published this repository trying to create a minimal and reproducible example: https://github.com/vvvctr/react-isolated-block-editor.

In the [README](https://github.com/vvvctr/react-isolated-block-editor#readme) you can see that I am getting the same errors reported in this issue and also some warnings I am getting on `npm install` (although I've tried `npm install --legacy-peer-deps` with similar results).

Please, let me know if I shoud open a new issue; I'll gladly do so.

Thanks for your prompt response!

**Comment by johngodley** [comment]
Your app doesn't appear to include Gutenberg. As explained in the [readme](https://github.com/Automattic/isolated-block-editor#bundling-and-wordpress) you will need to load this yourself.

If your app is loaded as part of WordPress then you can use the Gutenberg files from there. If not then you can use the files in https://github.com/Automattic/isolated-block-editor/tree/trunk/build-browser which does bundle Gutenberg (see https://github.com/Automattic/isolated-block-editor#standalone-module)

**Comment by vvvctr** [comment]
Sorry about that; I thought importing the "build-browser" script wouldn't work in a ESM context.
I [updated](https://github.com/vvvctr/react-isolated-block-editor/commit/03bf71bd04e451153fb829a899efae0e82f56d48) my code (1) and am getting this new error (2).

Now nothing renders.

(1)
```js 
import React from "react"

import '@automattic/isolated-block-editor/build-browser/core.css'
import '@automattic/isolated-block-editor/build-browser/isolated-block-editor.css'
import IsolatedBlockEditor, {
  DocumentSection,
  EditorLoaded,
  ToolbarSlot,
} from '@automattic/isolated-block-editor/build-browser/isolated-block-editor.js'
```

(2)
```
Uncaught ReferenceError: React is not defined
    at 7363 (isolated-block-editor.js:2:1)
    at n (isolated-block-editor.js:2:1)
    at isolated-block-editor.js:2:1
    at isolated-block-editor.js:9:1
    at ./node_modules/@automattic/isolated-block-editor/build-browser/isolated-block-editor.js (isolated-block-editor.js:9:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.js (bundle.js:19:130)
    at options.factory (react refresh:6:1)
```

**Comment by johngodley** [comment]
> I thought importing the "build-browser" script wouldn't work in a ESM context.

You will need to adjust things for your own environment, and this part you may have to do things that aren't documented - you're kind of on your own a bit here.

> React is not defined

The same thing. The docs have the details: https://github.com/Automattic/isolated-block-editor#standalone-module
