### ISSUE TITLE
[Question] How to style gutenberg itself?

### ISSUE THREAD

**Issue by adrianhm13** [Automattic/isolated-block-editor#169]
Sorry if the question doesn't fit here, but I'd like to ask if it's possible to manage the CSS from Gutenberg, I see that the components come directly from @wordpress with iframes so I suppose that changing icons and some styles can be rather difficult isn't it?

Thanks and have a great day!

**Comment by johngodley** [comment]
There are no iframes used here. You should be able to apply whatever CSS you need to the page directly. Icons for existing components will be trickier as they are from Gutenberg itself.

**Comment by adrianhm13** [comment]
Perfect, thanks a lot, time to start experimenting then. 

Have a nice week!
