### ISSUE TITLE
How do I fix toolbar from the first time?

### ISSUE THREAD

**Issue by nitinthewiz** [Automattic/isolated-block-editor#173]
Hi, the floating text toolbar that sits on top of every block is quite a PITA. I like that moreMenu has an option for Top Toolbar, but it doesn’t default to fixed. 

I tried setting user settings.editor.fixedToolbar to true, but that didn’t work. 

I also tried to access wp.data but that seems to be an internal dictionary.

Is there some public way to set the toolbar to fixed when Gutenberg takes over a textarea?

Thanks!

**Comment by fernandomm** [comment]
Setting it as a default preference works for me:

```
iso: {
  defaultPreferences: {
    fixedToolbar: true
  }
}
```

**Comment by nitinthewiz** [comment]
Thank you so much Fernando! That worked like a charm. Digging into the code, I noticed that the defaultPreferences seems to have only fixedToolbar in it. Are there no other default preferences?

Also, when I started playing with ISO, I noticed that the editor mode (visual vs code) was available in the more Menu, but now it's disappeared and no matter what I do, it won't come back. Even in the storyBlocks, when I'm testing it out, turning on or off the editor feature doesn't show the option in the moreMenu.

My config - 
```
                 const u_settings = {
			iso: {
				defaultPreferences: {
					fixedToolbar: true,
				},
				toolbar: {
					inspector: true,
					toc: true,
					// navigation: true,
					documentInspector: true,
				},
				moreMenu: {
					editor: true,
					fullscreen: true,
					preview: true,
					// topToolbar: true,
				},
			    sidebar: {
					inserter: false,
					inspector: true,
				},
			},
		};

		const textarea = document.querySelector('textarea');
		wp.attachEditor( textarea, userSettings = {...u_settings} );
```

I've tested this on the latest Chrome and the latest Firefox, both.

Any thoughts?

Is there any documentation I can refer to?

**Comment by nitinthewiz** [comment]
Ah, after I posted this message, I looked into the code and found isCodeEditingEnabled under the editor-menu.js

Enabling it by setting 

```
                       editor: {
				codeEditingEnabled: true,
			}
```

seems to work.

Thanks!
