### ISSUE TITLE
Improve toolbar defaults

### ISSUE THREAD

**Issue by johngodley** [Automattic/isolated-block-editor#19]
The toolbar needs some solid defaults that work across different width screens.

Here's what things look like on a small editor:

![image](https://user-images.githubusercontent.com/1277682/111163831-5e152f00-8595-11eb-83c0-38e3053d19e3.png)

The toolbar is correctly wrapping, but the style isn't quite right and it obscures the editor

**Comment by jasmussen** [comment]
To an extent, I think this worth fixing directly in the core project. Right now the stacked toolbar is an overlay that covers content even there, including the scrollbar. But it should not cover content, it should push the content down.

**Comment by johngodley** [comment]
That makes sense. I'll put together an issue over in Gutenberg.

I think there are some related padding issues specific to here, so I'll try and split those out so this issue is a bit more focussed.

**Comment by johngodley** [comment]
Here's a screenshot of the padding issue that often occurs, with the vertical grey lines not quite reaching the top or bottom:

![image](https://user-images.githubusercontent.com/1277682/111478154-b4b27280-8727-11eb-9488-d399b353ef10.png)

It's something to do with a height of 48px and 60px. I'll track down more details.
