### ISSUE TITLE
Translation and patterns in Standalone Module

### ISSUE THREAD

**Issue by xpalko** [Automattic/isolated-block-editor#195]
Hi,
I have just two questions:
1/ does the standalone editor also support patterns (in Wordpress "Toggle block inseter -> Patterns")?
2/ how do I add another language from the editor (for example czech)?
Thank you
PK

**Comment by johngodley** [comment]
1) Sure, it's the same editor and you can pass patterns in the same way
2) It's Gutenberg, so whatever you need to do there will work the same

**Comment by xpalko** [comment]
Thansk!

**Comment by xpalko** [comment]
Maybe I reopen this task with more information.

I just want to know if point 1/ and /2 are possilbe by some configuration in your built standalone editor isolated-block-editor.js or i must write some custom javascript and  built my own instance.

I'm not wordpress or gutenberg developer :) I'm trying using your built standalone editor isolated-block-editor.js in my project insted of tinymce.

I'm not wordpress or gutenberg developer :) I'm trying using your built standalone editor in my project.
