### ISSUE TITLE
It is not possible to change the height of the popover using css

### ISSUE THREAD

**Issue by ArtMin96** [Automattic/isolated-block-editor#207]
There are sections where it is not possible to make changes using CSS. What option would you suggest?
![user-menu](https://user-images.githubusercontent.com/29732308/212321961-3329d299-3d14-4647-9a33-1bceca43882e.png)

**Comment by johngodley** [comment]
I don't know what that is in the screenshot, but popovers are handled by Gutenberg. If you have problems with them then possibly your surrounding page content is restricting the height.

**Comment by ArtMin96** [comment]
Fixed:
```css
.iso-editor, .edit-post-layout {
    @apply h-screen;
}
```
