### ISSUE TITLE
content is not written in the textarea

### ISSUE THREAD

**Issue by ArtMin96** [Automattic/isolated-block-editor#209]
What is the problem that the content is not written in the textarea?
![user-menu](https://user-images.githubusercontent.com/29732308/212489557-1782e090-b664-4a8a-9381-967e9796de33.png)

```javascript
wp.attachEditor(editor, settings)
```

**Comment by johngodley** [comment]
If configured correctly the content is written to the textarea. It won't appear in your browser debugger in the way you seem to be suggesting as that isn't how your browser works.

**Comment by johngodley** [comment]
You can use the storybook for examples of how to use this project, as well as https://github.com/Automattic/blocks-everywhere/

**Comment by ArtMin96** [comment]
Thank you for the very quick response every time. How can I get the value? ex. `editor.getContent()`

**Comment by johngodley** [comment]
Why do you need to get the value? It's a textarea and will be included as part of whatever form is submitted.

**Comment by ArtMin96** [comment]
Wherever I should have used it, I don't need it anymore. Thanks
