### ISSUE TITLE
Question about iso.toolbar props

### ISSUE THREAD

**Issue by carolinan** [Automattic/isolated-block-editor#211]
Is there a way I can set the iso.toolbar props to always show the list view and the inspector, without the ability to toggle them on and off?

My current settings:
```
	'toolbar'     => array(
		'navigation' => true, // list view
		'inspector'  => true, // block settings sidebar
		'undo'       => true,
		'inserter'   => false, // block inserter at top left
		'documentInspector' => null, // document settings sidebar
		),

```

**Comment by johngodley** [comment]
No, it's not currently possible to do that. The logic matches how Gutenberg works.

**Comment by carolinan** [comment]
Thank you :)
