### ISSUE TITLE
editor change event

### ISSUE THREAD

**Issue by ArtMin96** [Automattic/isolated-block-editor#212]
Is there an event to detect changes in the editor?

**Comment by johngodley** [comment]
You can find usage details here:

https://github.com/Automattic/isolated-block-editor#usage

Also you can monitor any of the data stores in Gutenberg that change when blocks are modified.

**Comment by ArtMin96** [comment]
The problem is that I can't use it like this. I am integrating using alpine js. If there is another option, it will be great

**Comment by ArtMin96** [comment]
I need to follow the editor's state changes and perform some actions

**Comment by johngodley** [comment]
You will need to use either the callbacks shown on the usage guide, or access the Gutenberg stores. Those can be used with plain JS, and I'm sure it's possible to integrate them with any JS library.

**Comment by ArtMin96** [comment]
I tried to look for several options, but all of them are examples like this
```javascript
wp.data.select("core/some-package").getXXXXXXX()
```
And seems like we don't have those `wp.data`, `wp.block`, ...

**Comment by johngodley** [comment]
You can import them from Gutenberg like you would any other JS library.

You are probably going to have to get more familiar with Gutenberg if you want to use it for anything other than the basics.

**Comment by ArtMin96** [comment]
Yes, you are right. I try to get to know as much as possible. It is a bit difficult for a beginner because many things are not documented, and the existing ones are not well presented.
Thank you for such fast and efficient support.
