### ISSUE TITLE
still works?

### ISSUE THREAD

**Issue by VictorCataDAW** [Automattic/isolated-block-editor#223]
I am new in to this world of programming. I've been looking at wordpress and their gutenberg blocks and then this isolated block editor and the ability to add the sidebar editor. I have downloaded the code.zip, I have unzipped it and through the console I have tried to execute it but I have no result. I really don't know what to do to be able to run the sidebar editor, the isolated one can be run through a project at visual studio code. Can someone guide me on what I should do to be able to view it in the browser? Thanks and excuse my ignorance.

**Comment by johngodley** [comment]
Yes it still works. Tried to execute it how? What is the sidebar editor? I'm not sure what you mean about running it in VSCode, but it only runs in a browser.

**Comment by VictorCataDAW** [comment]
I mean... this is what I really see, is it?
<img width="993" alt="Captura de pantalla 2023-04-20 a las 13 13 24" src="https://user-images.githubusercontent.com/95479879/233349981-883d5d83-afe3-4f7d-a0bb-05fd61bf209b.png">

thank you in advance

**Comment by johngodley** [comment]
Yes, that is an example.

**Comment by VictorCataDAW** [comment]
ok, at this isolated block editor, when you choose a paragraph, it's possible to edit the code of this paragraph, as you can edit the code in wordpress ? 
<img width="1635" alt="Captura de pantalla 2023-04-20 a las 13 21 58" src="https://user-images.githubusercontent.com/95479879/233351456-8b7fd8ed-5d5f-48b4-8e9e-4b291200ad75.png">

thank you so much

**Comment by johngodley** [comment]
There are many options, including one for a visual/code edit mode:

https://github.com/Automattic/isolated-block-editor#props

**Comment by VictorCataDAW** [comment]
sorry for this question... how can I activate or modify these options?

**Comment by johngodley** [comment]
It should be detailed in the readme itself. You pass them in as the `settings` object. It's also shown in the example https://github.com/Automattic/isolated-block-editor/blob/trunk/src/browser/index.js

**Comment by johngodley** [comment]
Closing this for now, please reopen with more details.
