### ISSUE TITLE
Cannot unlock an object that was not locked before

### ISSUE THREAD

**Issue by kylefordui** [Automattic/isolated-block-editor#228]
I am attempting to use this in a React environment, without WordPress but am getting the following error, not sure why. I have included an image of the error with the code being used. Any help would be greatly appreciated, thank you. I am running in a React environment with Vite.

<img width="1276" alt="block-editor-error" src="https://github.com/Automattic/isolated-block-editor/assets/76667869/1709b498-5044-49b3-ab7a-d39119ad66ac">
<img width="500" alt="isolated-block-editor-code" src="https://github.com/Automattic/isolated-block-editor/assets/76667869/025b3ed4-0be5-474c-9613-05647da7286f">

**Comment by johngodley** [comment]
I don't know what locking does and it may not be supported here. Have you looked at the Gutenberg code?

https://github.com/WordPress/gutenberg/blob/4d0f303bf0bf231db12221f03548cbc067c302b1/packages/private-apis/src/implementation.js#L182

**Comment by kylefordui** [comment]
Wow thanks for the quick reply!
Yes I have had a look at that, I am not 100% sure what locking does either. I have just implemented the block editor as per the example above and am getting this error. Seems to be running the IsolatedBlock editor through an unlock function. Would you expect any errors from my example above? Not sure if / how I could exclude this unlock function as I don't think it will be needed.

**Comment by johngodley** [comment]
I would suggest supplying more props and some settings to the editor, as per the examples. You have probably triggered some error condition

**Comment by tobiasegli** [comment]
@kylefordui, I got the same error when I installed the @wordpress/data package at v9.5.0. It was gone once I installed the package at the version 9.1.0.

**Comment by wesleypeeters** [comment]
I can't seem to get rid of this. Weirdly enough, only the Vite build system seems to trigger this issue for me. Running the code OP provided in a CRA app will allow it to run successfully.

**Comment by AntonioJABV** [comment]
Same happening on our side.
Brand new **Vite** project, basic block editor, and just the same error in the console.

```jsx
function App() {
  return (
    <IsolatedBlockEditor>
      <EditorLoaded onLoaded={() => {}} onLoading={() => {}} />
      <DocumentSection>Extra Information</DocumentSection>

      <ToolbarSlot>
        <button>Beep!</button>
      </ToolbarSlot>
    </IsolatedBlockEditor>
  );
}
```

Output V2.25.0:
```log
14:13:06.559 implementation.js:182 Uncaught Error: Cannot unlock an object that was not locked before. 
    at unlock3 (implementation.js:182:9)
    at index.js:30:1
unlock3 @ implementation.js:182
(anonymous) @ index.js:30
```

Output V2.23.1:
```log
14:23:45.209 chunk-C6RUTG3L.js?v=775dde92:sourcemap:18255 Uncaught Error: Cannot unlock an object that was not locked before. 
    at unlock3 (chunk-C6RUTG3L.js?v=775dde92:sourcemap:18255:11)
    at node_modules/@wordpress/blocks/build-module/store/index.js (chunk-C6RUTG3L.js?v=775dde92:sourcemap:18327:5)
    at __init (chunk-CEIBQOFC.js?v=775dde92:sourcemap:16:56)
    at node_modules/@wordpress/blocks/build-module/index.js (chunk-C6RUTG3L.js?v=775dde92:sourcemap:26140:5)
    at __init (chunk-CEIBQOFC.js?v=775dde92:sourcemap:16:56)
    at node_modules/@wordpress/editor/build-module/hooks/custom-sources-backwards-compatibility.js (chunk-C6RUTG3L.js?v=775dde92:sourcemap:267695:5)
    at __init (chunk-CEIBQOFC.js?v=775dde92:sourcemap:16:56)
    at node_modules/@wordpress/editor/build-module/hooks/index.js (chunk-C6RUTG3L.js?v=775dde92:sourcemap:374619:5)
    at __init (chunk-CEIBQOFC.js?v=775dde92:sourcemap:16:56)
    at node_modules/@wordpress/editor/build-module/index.js (chunk-C6RUTG3L.js?v=775dde92:sourcemap:374774:5)
unlock3 @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:18255
node_modules/@wordpress/blocks/build-module/store/index.js @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:18327
__init @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:16
node_modules/@wordpress/blocks/build-module/index.js @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:26140
__init @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:16
node_modules/@wordpress/editor/build-module/hooks/custom-sources-backwards-compatibility.js @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:267695
__init @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:16
node_modules/@wordpress/editor/build-module/hooks/index.js @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:374619
__init @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:16
node_modules/@wordpress/editor/build-module/index.js @ chunk-C6RUTG3L.js?v=775dde92:sourcemap:374774
__init @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:16
node_modules/@automattic/isolated-block-editor/build/index.js @ @automattic_isolated-block-editor_build.js?v=775dde92:sourcemap:8561
__require2 @ chunk-CEIBQOFC.js?v=775dde92:sourcemap:19
(anonymous) @ @automattic_isolated-block-editor_build.js?v=775dde92:sourcemap:8635
```

If some required props are missing as specified in this message https://github.com/Automattic/isolated-block-editor/issues/228#issuecomment-1591004145, would you mind @johngodley sharing which ones are the minimum parameters required for making a working editor?

I've been searching them but I cannot manage to get the list of minimum required parameters. I've been two days fighting with this issue, without solution yet. All help is pleased 🙏 

Best regards,
Antonio,

**Comment by johngodley** [comment]
I suspect you were using different versions of the `@wordpress` packages than is supported by this repo. 2.26.0 has updated the packages and that may solve some of these issues.

**Comment by AntonioJABV** [comment]
Perfect. On my side it has been fixed automatically when I upgraded to version `^2.26.0` 😉

**Comment by stevep** [comment]
For anyone else still running into this, I had to make sure I was loading the version of `wp-private-apis` that WordPress supply's rather than bundlilng my own from node_modules, because I was also relying on the version of `wp-block-editor` that WordPress supply's.

**Comment by wesleypeeters** [comment]
@stevep How do you mean? I just upgraded to `^2.26.0`, but am still running into this issue. After some sleuthing, I saw that `@wordpress/private-apis` is in my yarn.lock twice. Once `@^0.19.0`, `@^0.20.0`. Could this be whats caussing my issue?

**Comment by wesleypeeters** [comment]
I managed to identify a cause and temporary solution. Initially, I installed `isolated-block-editor@^2.26.0` in an isolated environment and it worked as expected. After conducting an in-depth comparison of yarn lockfiles, I surmised that the problem was version-related.

As a workaround, I used Yarn's resolutions feature to fix the versions of the `@wordpress/*` packages required by `@automattic/isolated-block-editor`. (This was done by transferring these dependencies from the project's `package.json` file into the `resolutions` array in my own `package.json` file.) 

For me, this is just a stopgap measure, and I am still in search of a more permanent solution addressing the underlying issue. I hope this insight assists with troubleshooting and resolution of this issue.

**Comment by triopter** [comment]
@welsipieters - What versions did you need to lock which packages to?

**Comment by johngodley** [comment]
Gutenberg's modules are sometimes incompatible with different versions of other modules, and there's no easy way to handle this. The versions listed in the project `package.json` are known to be working versions (a snapshot from a particular version of Gutenberg), but anything outside of that may or may not work. Gutenberg moves at a much faster speed than this project can keep up with, so it's not possible to ensure that everything is always going to work with newer versions of Gutenberg.

I'm going to close this issue as it looks to be 'solved'.
