### ISSUE TITLE
WP 6.3 compatibility: __experimentaluseLayoutClasses is not a function

### ISSUE THREAD

**Issue by ryelle** [Automattic/isolated-block-editor#229]
I'm trying to upgrade WordPress & Gutenberg on wordpress.org, and am running into a javascript error from [blocks-everywhere](https://github.com/Automattic/blocks-everywhere/), but I think I've tracked it down to this project.

The forums editor is perpetually loading, and the following error appears in console.

<img width="400" alt="Screenshot 2023-07-10 at 1 34 15 PM" src="https://github.com/Automattic/isolated-block-editor/assets/541093/2b15eb9c-6073-434f-90dc-48cbff01dc70">

```
TypeError: _wordpress_block_editor__WEBPACK_IMPORTED_MODULE_2__.__experimentaluseLayoutClasses is not a function
    VisualEditor visual-editor.js:204
    St react-dom.min.js:1
    $s react-dom.min.js:1
    Sl react-dom.min.js:1
    kl react-dom.min.js:1
    bl react-dom.min.js:1
    sl react-dom.min.js:1
    il react-dom.min.js:1
    v react.min.js:1
    ce react.min.js:1
    t react.min.js:1
    <anonymous> react.min.js:1
    <anonymous> react.min.js:1
react-dom.min.js:1:53535
```

Environment:
- WordPress 6.3-beta3-56184
- Happens with Gutenberg 16.1.2 or with GB deactivated. If I try to roll back GB between 15.7-16.0 it causes a fatal error with core, but if I roll back to GB 15.6.2 everything works correctly.

**Comment by alshakero** [comment]
For the next person who sees this. We're investigating this. And it's due to this change in Gutenberg. 

https://github.com/WordPress/gutenberg/pull/51434

**Comment by johngodley** [comment]
I have fixes for this and a bunch of other issues, but it will take a bit of time to release through the chain. For now the only compatible version of Gutenberg is < 15.6, and the packages specified in `package.json`

**Comment by alshakero** [comment]
Hi John 👋🏼  That's great! 

Do you have a rough timeline? This issue is blocking our project here: pdDR7T-OS-p2

We'd be happy to help review PRs, help deploy, etc..

**Comment by tellthemachines** [comment]
Unfortunately `__experimentaluseLayoutClasses` was never meant for public consumption, and being experimental means WP doesn't guarantee its continued availability or back-compat. It's now been made a [private API](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-private-apis/).

Having said that, I'm interested in knowing more about this particular use case for the function, because if it's something that could be handy for extenders it could perhaps be made into a public API in the future. Whereabouts could I find out more about it?

**Comment by johngodley** [comment]
@alshakero can you not use a compatible version of Gutenberg - is there something specific you need from a recent version?

**Comment by alshakero** [comment]
@johngodley we're running this on wp.com, I have no control of the GB version there :(
