### ISSUE TITLE
WordPress 6.4 Support

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/isolated-block-editor#238]
Hello @johngodley, first of all, thank you for all of your great work on this project -- it's immensely helpful.

I'm wondering about your plans for supporting multiple versions of WordPress when the `lock`/`unlock` needs to be updated for each major WordPress version?

https://github.com/WordPress/gutenberg/issues/49784

Changing it to support `6.4` will break `6.3`, etc.

FYI -- that change seemed all that was needed for testing the latest Gutenberg nightly (in my usage).

**Comment by johngodley** [comment]
It's difficult enough supporting one version and there are no plans to support more!

**Comment by spencerfinnell** [comment]
So the plan is always the latest official major release of WordPress?

**Comment by spencerfinnell** [comment]
Draft PR #239 has my findings for `6.4` support.

**Comment by johngodley** [comment]
Unfortunately it's not that straightforward. This project is only tested against specific versions of Gutenberg libraries, and the recommendation (if you are using it on a WP site) is to use the Gutenberg plugin that matches those versions.

The mapping between the plugin and the version of Gutenberg built into WordPress is not simple, and I can't say which version it will work with. Often the built-in version won't work as it's a few months older and doesn't provide the functions that this project relies on. Right now the version in WordPress is much newer.

**Comment by spencerfinnell** [comment]
Right. I know it's a jumble. 

I had been using the isolated editor with WordPress 6.3 (no Gutenberg plugin), then installed Gutenberg nightly and the changes in the PR were all I found that were needed to support it -- previously there were a lot more incompatibilities. 🤷🏻 

Feel free to close both the issue and PR if they aren't relevant to the planned update process.

**Comment by spencerfinnell** [comment]
Implemented via  https://github.com/Automattic/isolated-block-editor/pull/245
