### ISSUE TITLE
Uncaught Error: Cannot unlock an object that was not locked before. 

### ISSUE THREAD

**Issue by 23creative** [Automattic/isolated-block-editor#247]
I have cloned a copy of this package run `npm install --save-dev`

if i navigate to `src/browser/index.html` editor loads as expected.

I have cloned a copy of this package run `npm run build` then if a navigate to `src/browser/index.html` the error `Uncaught Error: Cannot unlock an object that was not locked before.` my console.

I have gone through all the docs and tried to get the Isolated browser running. I don't suppose anyone has the same problem? I would be willing to pay for someone to fix this for me

**Comment by 23creative** [comment]
no it looks like im an idiot. sorry

**Comment by andreibrindas** [comment]
What have you done to fix the error? I also run into this one...
Thanks!
