### ISSUE TITLE
Remove deprecated block-toolbar slot

### ISSUE THREAD

**Issue by johngodley** [Automattic/isolated-block-editor#25]
With Gutenberg 10.7.1 it's now reporting this warning:

`wp.components.Popover.Slot name="block-toolbar" is deprecated`

**Comment by johngodley** [comment]
Looking at this some more it seems that Gutenberg now uses a double-height toolbar:

![image](https://user-images.githubusercontent.com/1277682/127495581-be6a1581-2ed9-41c2-9ab3-787097a087e8.png)

The first line is in the toolbar, and the second line is in the content. I don't think it will be possible to use CSS to merge them together.

For the purposes of the editor here the extra line can look a bit heavy when used in a small editor situation:

However, it does solve some of the problems we have when toolbars get too long for a single row.

**Comment by johngodley** [comment]
Gutenberg seems to be moving in a direction where we will be forced to accept the double-height toolbar in order to retain certain features (for example, deletion of multiple blocks).

As mentioned in https://github.com/Automattic/isolated-block-editor/pull/44#issuecomment-913751761, the problem for the Isolated Editor is that some contexts might look clumsy with a toolbar that could take up more vertical space than the content itself. For example, P2 comments.

I wonder if a compromise is to go with the double-height and force an inline toolbar in situations that require a lighter toolbar. For mobile users, the forced inline toolbar would become a double-height toolbar in the same way it does now in core Gutenberg.

This would have the added benefit of fixing the problem of the single toolbar overflowing when too many buttons are added.

If we desired a single line toolbar in the future then it would need to be worked into Gutenberg itself.

@evilluendas do you think this would work for P2?

If it helps visualize the change then this is what the editor will look like when the toolbar is not showing anything:

![image](https://user-images.githubusercontent.com/1277682/133620754-3d21ab2c-ead4-4091-9814-6896bea4669e.png)

And when showing:

![image](https://user-images.githubusercontent.com/1277682/133620827-0ae200a7-6bad-4b27-9103-cb713cbd09ef.png)

This is in contrast to the current single height toolbar:

![image](https://user-images.githubusercontent.com/1277682/133620987-ff2877c0-3b49-4d5d-a888-7d5d03b93d7f.png)

**Comment by evilluendas** [comment]
Hmm, interesting! I think in general we should stay as in sync with Gutenberg as possible, even in these situations, so we'll have to make it work 😄 

The double toolbar only appears when the "Top toolbar" option is selected, right? Maybe we could force it to be disabled in smaller viewports so the toolbar is floating?

https://user-images.githubusercontent.com/820374/133646072-dd634fbe-e5b9-4bf6-bfae-178316827def.mov

I suspect the idea is to align the lines with the sidebar so it looks fine even if the toolbar is empty, so I'm looking forward to making the Settings popover become a proper sidebar — that way it'll look less strange, I think.

![image](https://user-images.githubusercontent.com/820374/133646347-f75d06e3-91fd-4af4-9113-08f0a2c727dd.png)

I guess the ideal would be to have a "super simple mode" in Gutenberg that only displays the basic stuff, maybe just the block tools and hide the top bar, so it can be used in tiny places.
