### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by scinos** [Automattic/isolated-block-editor#33]
Is this package available in NPM?

When I [search for it](https://www.npmjs.com/package/isolated-block-editor), I get a "Security holding package":

![image](https://user-images.githubusercontent.com/975703/126261409-cf76ab12-f75b-4138-af4a-610ed19ae857.png)

**Comment by johngodley** [comment]
Maybe in the future, but right now it is not on NPM (#9)

**Comment by johngodley** [comment]
Marking as done, thanks!
