### ISSUE TITLE
Collab: Jump focus to peer-selected block when avatar is clicked

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#56]
When a peer's presence avatar is clicked, it could jump to the block that the peer is currently editing.

**Comment by mtias** [comment]
You'd want to look at `selectBlock( clientId )`

**Comment by lamosty** [comment]
If multiple blocks are selected, should we jump to the first one?

**Comment by mirka** [comment]
> If multiple blocks are selected, should we jump to the first one?

Sounds good to me.
