### ISSUE TITLE
Collab: Profiles are cramped and shifted when block toolbar has too many options

### ISSUE THREAD

**Issue by zdenys** [Automattic/isolated-block-editor#64]
For blocks that have many toolbar options ([Heading Block](https://wordpress.com/support/wordpress-editor/blocks/heading-block/), [Blog Posts Block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/), etc.), the profiles of the peers are shifted to the top-right and appear cramped. 

![Screen Capture on 2021-09-22 at 16-45-21](https://user-images.githubusercontent.com/39308239/134513219-e5495162-246f-4a1b-a994-861a4e6c4fc6.gif)

The various three-dots menus are all over the place.

![image](https://user-images.githubusercontent.com/39308239/134514146-c2c49991-c68c-4ec9-91b9-218be7a54528.png)

---
Discovered as part of team testing p9ag8j-1D4-p2#comment-4081

**Comment by johngodley** [comment]
Yep, this is a known issue and will hopefully be taken care of when https://github.com/Automattic/isolated-block-editor/pull/62 is merged.

**Comment by mirka** [comment]
Closed by #62
