### ISSUE TITLE
Deprecation warning for `Popover.Slot name="block-toolbar"`

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#80]
We're getting a deprecation warning (seen in the Storybook build):

```
wp.components.Popover.Slot name="block-toolbar" is deprecated. Please use wp.blockEditor.BlockTools instead.
```

**Comment by johngodley** [comment]
This should have been fixed with the new toolbar. Is the storybook using an older version?

**Comment by mirka** [comment]
Ah, makes sense, I wasn't on trunk! 🤦 Thanks
