### ISSUE TITLE
Add Renovate for `@wordpress` packages

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#93]
I think it would be good to add some Renovate config to help update our `@wordpress/*` dependencies.

## Benefits

- It will prompt us to update the WP deps without too much delay. We have seen at least one iso-editor consumer having to wait on our package updates (https://github.com/Automattic/crowdsignal-ui/pull/94). Similar problems can happen in a dependency-extracted environment.
- In combination with some good integration tests running on the auto-opened Renovate PRs, it can flag integration failures as soon as possible. This will give us a better head start at addressing the issues.

I'm thinking we should limit the Renovate scope to only `@wordpress` packages for now and gradually expand the scope if it's worth the upkeep.

**Comment by johngodley** [comment]
I'm not too worried about the @wordpress packages being a bit out of date, and I suspect we could run into auto-updated problems that will be hard to catch with integration tests.

Is it possible to group the updates? I find the bot is a bit noisy, and a lot of the time the updates aren't particularly important and don't require a new release of the package. Could it alert us for major updates so they can be manually tested?

**Comment by mirka** [comment]
All valid concerns!

Yes, the monorepo packages will arrive as a single PR like this, from which we can skim the diffs/changelogs if necessary. Renovate is very configurable, so I believe we can even do something like "group both major and minor updates into a single PR (for easier testing), but add a `major` warning when there are major updates in the batch".

![Screenshot of a Renovate PR opened for the @wordpress monorepo](https://user-images.githubusercontent.com/555336/143941478-c4981448-da57-4571-bebc-81419a4b93ec.png)

I agree we should turn **auto-merge off**, and only use this as a prompt/dashboard/jumping-off point for manual testing. I imagine the actual manual test/merge/release will happen right after Gutenberg plugin releases. Apart from those specific times where it requires human intervention, we can mostly ignore the Renovate PR and it will simply serve as a canary for possible early detection of integration issues.

How does that sound?

**Comment by johngodley** [comment]
Sounds great, let's do it.
